name: Respond to Guesses

on:
  discussion_comment:
    types: [created]

jobs:
  check-guess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to check guess
        run: python scripts/check_guess.py
        env:
          DISCUSSION_ID: ${{ github.event.discussion.id }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_ID: ${{ github.event.comment.id }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
